# Gradle Properties
	org.gradle.jvmargs=-Xmx6G

# Fabric Basic Properties
	# https://fabricmc.net/versions.html
	loader_version=0.19.3

# Mod Properties
	mod_id=safk
	mod_name=SaveAFK
	mod_author=T3rr0or
	mod_version=0.1.0
	maven_group=io.qxl.safk
	archives_base_name=safk

# Global Dependencies
	# https://github.com/Fallen-Breath/conditional-mixin
	conditionalmixin_version=0.6.4

	# https://github.com/LlamaLad7/MixinExtras
	mixinextras_version=0.3.6

# Dependencies
	# https://github.com/sakura-ryoko/corelib
	corelib_version = 0.2.15
